CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (3,)
LOG_DIR: 'exp'
WORKERS: 12
PRINT_FREQ: 100

DATASET:
  DATASET: NWPU
  ROOT: '../ProcessedData/NWPU_2048/'
  TEST_SET: 'val.txt'
  TRAIN_SET: 'train.txt'
  NUM_CLASSES: 1
  DEN_FACTOR: 200
MODEL:
  NAME:  internet #seg_hrnet # VGG16_FPN
  PRETRAINED: '/media/D/GJY/ht/PretrainedModels/hrnetv2_w48_imagenet_pretrained.pth'
  EXTRA:
    FINAL_CONV_KERNEL: 3
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM
LOSS:
  USE_OHEM: false
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
TRAIN:
  IMAGE_SIZE:
  - 1024
  - 1024
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 300
  RESUME: false
  RESUME_PATH: None # './exp/NWPU/VGG16_FPN/cc_vgg16_fpn_2022-05-26-12-30'
  OPTIMIZER: Adam  #sgd
  LR: 5e-5
  WD: 0.00001
  MOMENTUM: 0.9
  NESTEROV: false   #@for sgd
  AMSGRAD: false #for Adam
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 2048
  - 1024
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 1
  PATCH_BATCH_SIZE: 16
  FLIP_TEST: false
  MULTI_SCALE: false
